---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:


   - name: ec2 provisioning
     ec2:
        aws_access_key: AKIAIYK5LBYWIQOMB6PA
        aws_secret_key: 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
        key_name: agility_keypair
        region: ap-southeast-1
        instance_type: t2.micro
        image: ami-96f1c1c4
        wait: yes
        exact_count: 1
        count_tag:
           Name: Test
        instance_tags:
           Name: Test
     register: ec2
	 
  - name: Gathering ec2 facts
    action: ec2_facts

