---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
   - /var/lib/jenkins/workspace/infra_as_code/infra/code/vars_aws.yml
  tasks:


   - name: ec2 provisioning
     ec2:
        key_name: agility_keypair
        region: ap-southeast-1
        instance_type: t2.micro
        image: ami-96f1c1c4
        wait: yes
        exact_count: 1
        count_tag:
           Name: Test
        instance_tags:
           Name: Test
     register: ec2

   - name: Wait for SSH to come up
     wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
     with_items: ec2.instances

   - name: Instance Register
     local_action:
      module: ec2_elb
      region: ap-southeast-1
      instance_id: "{{ item.id }}"
      ec2_elbs: test
      state: present
     with_items: ec2.instances
