---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
   - vars_aws.yml
  tasks:


   - name: ec2 provisioning
     ec2:
        key_name: agility_keypair
        region: ap-southeast-1
        instance_type: t2.micro
        image: ami-96f1c1c4
        wait: yes
        exact_count: 1
        count_tag:
           Name: Test
        instance_tags:
           Name: Test
     register: ec2
   - debug: var=ec2.instances.stdout_lines

   - name: Instance Register
     local_action:
      key_name: agility_keypair
      module: ec2_elb
      region: ap-southeast-1
      instance_id: "{{ item }}"
      ec2_elbs: test
      state: present
     with_items: ec2.instance_ids
