---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:


   - name: ec2 provisioning
     ec2:
        aws_access_key: AKIAJUNKIYK5LBYWIQOMB6PA
        aws_secret_key: m3FFJUNK1WMrF7EJKzg0e5mhNxuPbk8fuygpVlZHxsuN
        key_name: agility_keypair
        region: ap-southeast-1
        instance_type: t2.micro
        image: ami-96f1c1c4
        wait: yes
        exact_count: 1
        count_tag:
           Name: Demo
        instance_tags:
           Name: Demo
     register: ec2

